### ISSUE TITLE
uri tag in metrics set as NOT_FOUND instead of the actual service uri when response status is 404

### ISSUE THREAD

**Issue by AdityaBhansali1** [micronaut-projects/micronaut-micrometer#160]
Raising this issue as a follow up from the discussion here - https://github.com/micronaut-projects/micronaut-micrometer/issues/28#issuecomment-705479671

When a service responds with 404, we see the status tag in metric set correctly to 404 but the uri tag is set as hardcoded "NOT_FOUND" as seen [here](https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java#L263)

In our project we are using this metric to show different alerts based on different uri. This strategy doesn't work with the uri being hardcoded as "NOT_FOUND".

**Comment by pbthorste** [comment]
I am guessing that the reason why the URI tag is replaced with NOT_FOUND is because otherwise it would be possible to create alot of new metric dimensions by testing different urls.

But for the case where NOT_FOUND is a valid response, it is very inconvenient that the URI is not available as a tag.

Would it be possible to include a config switch so that NOT_FOUND does not remove the uri ?

**Comment by ychoy-brex** [comment]
Would it make sense for the logic to be replace URI iff no URI template was matched here https://github.com/micronaut-projects/micronaut-micrometer/blob/2c603fc55e0c9f00735b866d31db118f1123b1be/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/ServerRequestMeterRegistryFilter.java#L59?

That would still prevent cardinality of this tag from exploding, but would not unnecessarily replace URI on application-level `NOT_FOUND`.

**Comment by graemerocher** [comment]
making it configurable and disabled by default is an option. PRs welcome.
