### ISSUE TITLE
 Handled exceptions incorrectly report response code of 500

### ISSUE THREAD

**Issue by damianw** [micronaut-projects/micronaut-micrometer#28]
For a situation like the following:
```Kotlin
class MyException : Exception()

@Controller("/")
class MyController {
    @Get("/")
    fun get(): Any {
        throw MyException()
    }
}

@Singleton
class MyExceptionHandler : ExceptionHandler<MyException, HttpResponse<JsonError>> {
    override fun handle(request: HttpRequest<*>, exception: MyException): HttpResponse<JsonError> {
        return HttpResponse
            .status<JsonError>(HttpStatus.GONE)
            .body(JsonError("Should be reported as a 410"))
    }
}
```

Even though a GET to `/` returns a status of `410`, it is always reported in the metrics as `500`.

**Comment by jaksah** [comment]
We are experiencing this issue in 2.0.2 as well. I created a [sample project to reproduce this](https://github.com/jaksah/micronaut-error-metrics) (before I found this issue) if it would be of any help. Any ideas of a workaround?

**Comment by euler1337** [comment]
Inspired by the sample project @jaksah provided I created a [sample project](https://github.com/euler1337/micronaut-metrics-issue) to reproduce a similar in 2.0.2.

I noted that without the `micronaut-security` module (i.e. expecting the controller to return a 404 for a non existing route instead of a 401) the test passes as metrics are reported on 404.

**Comment by euler1337** [comment]
After looking a bit more into this, it seems like the issue is not new in 2.0. However in 2.0 micronaut-security introduces the new [rejection handler ](https://micronaut-projects.github.io/micronaut-security/latest/guide/#_rejection_handler) and the `AuthorizationException`. It seems to me like this new model makes this issue more visible than in previous releases, since the `AuthorizationException` will generate 500-metrics even if it is handled. 

@alvarosanchez Is it possible to say anything about the timeframe for this issue?

**Comment by brunovale91** [comment]
I believe there's a workaround for this issue, the WebMetricsPublisher checks if the exception is instance of HttpResponseProvider and then uses the status code defined on the exception.
`class NotFoundException(message: String) :
    RuntimeException(message), HttpResponseProvider {
    /**
     * Required for micrometer registry 404 metric
     */
    override fun getResponse(): HttpResponse<*> {
        return HttpResponse.notFound<Void>()
    }
}
`
I've tested this with prometheus and it registers 404.

**Comment by euler1337** [comment]
Thanks @brunovale91. I guess this workaround will do as long as you define your own exception and throw it from the application. However, im the case i describe above the `AuthorizationException` in micronaut-security does not implement `HttpResponseProvider`

**Comment by AdityaBhansali1** [comment]
In our case, even after doing the change suggested above, we still face the problem because our endpoint returns a CompletableFuture and hence our CustomException which implements HttpResponseProvider is wrapped inside a CompletionException.

The above use case causes the if condition at this [line ](https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java#L332)to fail as CompletionException doesn't implement HttpResponseProvider.

Is there any other workaround we could use to solve this issue?

**Comment by graemerocher** [comment]
Seems like me the solution is to make https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java#L330 extensible so that users can plugin handling of when and how they want exception metrics reported. 

Would that provide a solution?

**Comment by jameskleeh** [comment]
@AdityaBhansali1 @euler1337 @brunovale91 @jaksah @damianw I've created a PR which I believe resolves this issue. https://github.com/micronaut-projects/micronaut-micrometer/pull/156. Please check out that branch locally and verify that resolves the problem.

**Comment by AdityaBhansali1** [comment]
@jameskleeh : We upgraded micronaut to 2.1.0 and tried this out. We see the metrics being sent with proper status code ( 404 in my case ) now!

However, it looks like the metrics "uri" tag is coming up improperly as "NOT_FOUND" instead of the service uri. Is this a bug, or something consumers have to do additionally in code to handle?

**Comment by jameskleeh** [comment]
@AdityaBhansali1 Hard to say. Please create a separate issue with an example app that reproduces the issue and we'll take a look

**Comment by AdityaBhansali1** [comment]
@jameskleeh : We debugged this a little and found that the uri is being set to "NOT_FOUND" [here](https://github.com/micronaut-projects/micronaut-micrometer/blob/master/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMetricsPublisher.java#L263).

Is this the expected metrics behavior for micronaut metrics with status 404?

In our project we are using this metric to show different alerts based on different uri. This strategy doesn't work now with the uri being hardcoded as "NOT_FOUND".

**Comment by graemerocher** [comment]
That does seem odd behaviour. @ctoestreich can you elaborate on this why the URI tag is set to NOT_FOUND here?

**Comment by ctoestreich** [comment]
Looking at it I think it needs to be simplified. Only when the path is null should it NOT just sanitize and return the path.

**Comment by graemerocher** [comment]
@AdityaBhansali1 can you report a separate issue to track this?

**Comment by AdityaBhansali1** [comment]
Thank you all for taking a look into this! As per suggestion I have raised a new issue - https://github.com/micronaut-projects/micronaut-micrometer/issues/160
