### ISSUE TITLE
No http.server.requests metric with status=401 is reported

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-micrometer#39]
When auth fails on secured endpoints there are no metrics with status=401 reported.

Micronaut 1.2.1
See https://github.com/luckyswede/micronaut-metricstest

**Comment by oscarfh** [comment]
@graemerocher I am having the same issue and I would like to create a Pull Request. My suggested approach would be to be able to set the order (using application.yaml configuration) so the user can set the filter to be ordered before the security filter.
Would that be acceptable?

**Comment by graemerocher** [comment]
That is one approach and may do. I think the security filter should expose a constant that defines the order. Also maybe we need something like IntercepterPhase for filters. Thoughts @jameskleeh ?

**Comment by oscarfh** [comment]
The security filter does not expose the order, by one is able to set by creating an SecurityFilterOrderProvider, as it can be [seen here](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/filters/SecurityFilter.java#L85).

This is one alternative and is more flexible than the property, in case one wants to decide something dynamically. 
Can you elaborate on your idea of the InterceptPhase? I am not used to this class.

Anyway, let me know your preferred approach and I will do my best to create a PR.

**Comment by oscarfh** [comment]
@graemerocher Do you have some feedback on the PR?

**Comment by jameskleeh** [comment]
@oscarfh I'll be reviewing this today

**Comment by jameskleeh** [comment]
@oscarfh Please try with the latest 1.2.x security snapshot. The issue should be resolved

**Comment by oscarfh** [comment]
Ok, I will try that tomorrow, thanks

**Comment by jameskleeh** [comment]
@oscarfh So currently the session, metrics, and security filter are all running on order 0. That means that the order is non deterministic, however both the session and metrics filter must run before. We currently have in place the mechanism to move the filter forward to 100 if there is no other filter order bean and the session configuration is enabled.

Changing the filter order is required in order to fix this issue. Whether that means moving the metrics filter back or moving the security filter forward, the same issue may arise with existing filters either requiring to be before/after the metrics filter or before/after the security filter.

> every new Filter will, by default, run before the Security Filter

That isn't quite correct. There are other factors in play. Every new filter that has an order of less than 100 in an application that is not pegging the security filter order and has either session or metrics enabled will run before the security filter.

This whole situation is due to not having a filter phase system which we will implement, however that would absolutely be a breaking change to all applications. This is still a breaking change, however it has the least impact necessary to resolve the issue.

**Comment by oscarfh** [comment]
Ok, so order==100 will be executed before order==0.
I thought it was the other way around and got, so the logic was somehow "backwards" in my head. Thanks for the explanation.

**Comment by jameskleeh** [comment]
@oscarfh No your original thinking is correct. The highest precedence is the lowest number

**Comment by oscarfh** [comment]
Yes, I was just reviewing that and notice that (therefore deleted the comment in the hope you didn't need to read it).
Got it. Thanks for the explanation.
