### ISSUE TITLE
The @Timed annotation is not timing kotlin suspend functions correctly

### ISSUE THREAD

**Issue by stottpaul** [micronaut-projects/micronaut-micrometer#70]
Since replacing rxJava with kotlin suspend functions in our controllers, the @Timed annotation (applied to the controller method) is measuring requests as completing in < 1ms, whereas the wall time of the method is nearer 100ms.   nb. Usage is with histogram = true.

**Comment by markjfisher** [comment]
Hi @graemerocher I see this appears to be fixed in micronaut-micrometer, but that hasn't had a release since March. Is there somewhere I can go to find out when the scheduled releases are due for other sub-projects? I've been keenly watching the main micronaut releases (well, once a week at least :D ) to see if this bug is included in there, but it doesn't appear as though it has yet, particularly as micronaut-micrometer is still at 1.3.1 from March. Thanks

**Comment by ilopmar** [comment]
@markjfisher We have released a few versions after 1.3.1, please check: https://github.com/micronaut-projects/micronaut-micrometer/releases

**Comment by markjfisher** [comment]
I'm having a bad day.
I hadn't noticed the path has changed to io.micronaut.micrometer, so was looking at the older version.

**Comment by ilopmar** [comment]
No worries
